all: stl stl_sla rendering
stl:
	openscad -o HousingAll.stl generatePrintFile.scad
stl_sla:
	openscad -o HousingAll_SLA.stl generatePrintFile_SLA.scad
rendering:
	openscad -o HousingAssembled.stl generateRendering.scad
