all: stl stl_sla rendering
stl_sla:
	openscad -o HousingAll.stl generatePrintFile.scad
stl:
	openscad -o HousingAll.stl generatePrintFile.scad
rendering:
	openscad -o HousingAssembled.stl generateRendering.scad
